version: "3.9"

services:
  python3.7:
    image: public.ecr.aws/layerai/executor:python3.7${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        - PYTHON_VERSION=3.7.13
        - PIP_VERSION=22.2.2

  python3.8:
    image: public.ecr.aws/layerai/executor:python3.8${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: docker/Dockerfile
      args:
        - PYTHON_VERSION=3.8.13
        - PIP_VERSION=22.2.2

  python3.7-gpu:
    image: public.ecr.aws/layerai/executor:python3.7-gpu${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: docker/python3.7-gpu.Dockerfile

  python3.8-gpu:
    image: public.ecr.aws/layerai/executor:python3.8-gpu${TAG_SUFFIX:-}
    build:
      context: ./
      dockerfile: docker/python3.8-gpu.Dockerfile
